/**
 * Public Dogpile SDK exports.
 *
 * The primary high-level entrypoints are `run()`, `stream()`, and
 * `Dogpile.pile()`. Types exported from this module describe the single-call
 * result shape, streaming events, serializable traces, transcripts, and the
 * low-level engine escape hatch.
 */
export { Dogpile, createEngine, replay, replayStream, run, stream } from "./runtime/engine.js";
export { createOpenAICompatibleProvider } from "./providers/openai-compatible.js";
export { consoleLogger, loggerFromEvents, noopLogger } from "./runtime/logger.js";
export type { Logger, LoggerFromEventsOptions, LogLevel } from "./runtime/logger.js";
export { DEFAULT_RETRYABLE_DOGPILE_CODES, withRetry } from "./runtime/retry.js";
export type { RetryAttemptInfo, RetryJitterMode, RetryPolicy } from "./runtime/retry.js";
export { DogpileError } from "./types.js";
export type {
  OpenAICompatibleChatCompletionChoice,
  OpenAICompatibleChatCompletionResponse,
  OpenAICompatibleFetch,
  OpenAICompatibleProviderCostContext,
  OpenAICompatibleProviderCostEstimator,
  OpenAICompatibleProviderOptions,
  OpenAICompatibleUsage
} from "./providers/openai-compatible.js";
export {
  builtInDogpileToolIdentity,
  builtInDogpileToolInputSchema,
  builtInDogpileToolPermissions,
  createCodeExecToolAdapter,
  createRuntimeToolExecutor,
  createWebSearchToolAdapter,
  normalizeBuiltInDogpileTool,
  normalizeBuiltInDogpileTools,
  normalizeRuntimeToolAdapterError,
  runtimeToolAvailability,
  runtimeToolManifest,
  validateBuiltInDogpileToolInput
} from "./runtime/tools.js";
export type {
  BuiltInDogpileRuntimeTool,
  BuiltInDogpileToolDefinition,
  BuiltInDogpileToolExecutors,
  BuiltInDogpileToolIdentityOptions,
  CodeExecDogpileToolDefinition,
  CodeExecSandboxExecutor,
  CodeExecToolAdapterOptions,
  CodeExecToolExecutor,
  CodeExecToolInput,
  CodeExecToolLanguage,
  CodeExecToolOutput,
  DogpileBuiltInToolName,
  RuntimeToolExecutorOptions,
  WebSearchDogpileToolDefinition,
  WebSearchFetch,
  WebSearchFetchRequest,
  WebSearchFetchRequestBuilder,
  WebSearchFetchResponseParser,
  WebSearchToolAdapterOptions,
  WebSearchToolExecutor,
  WebSearchToolInput,
  WebSearchToolOutput,
  WebSearchToolResult
} from "./runtime/tools.js";
export {
  budget,
  combineTerminationDecisions,
  convergence,
  evaluateBudget,
  evaluateConvergence,
  evaluateFirstOf,
  evaluateJudge,
  evaluateTermination,
  evaluateTerminationStop,
  firstOf,
  judge
} from "./runtime/termination.js";
export type {
  AbortedEvent,
  AgentSpec,
  AgentDecision,
  AgentParticipation,
  BroadcastContribution,
  BroadcastEvent,
  BroadcastProtocolConfig,
  Budget,
  BudgetCaps,
  BudgetCostTierOptions,
  BudgetTier,
  BudgetStopEvent,
  BudgetStopReason,
  BudgetTerminationCondition,
  ConfiguredModelProvider,
  ConvergenceTerminationCondition,
  CoordinationProtocolSelection,
  CostSummary,
  CoordinatorProtocolConfig,
  DelegateAgentDecision,
  DogpileErrorCode,
  DogpileErrorOptions,
  DogpileOptions,
  Engine,
  EngineOptions,
  RunCallOptions,
  FinalEvent,
  FirstOfTerminationCondition,
  FirstOfTerminationConditions,
  FirstOfTerminationInput,
  FirstOfTerminationOutput,
  FirstOfTerminationStopRecord,
  JudgeAcceptDecision,
  JudgeEvaluationDecision,
  JudgeRejectDecision,
  JudgeScoreDecision,
  JudgeStopReason,
  JudgeTerminationCondition,
  JsonObject,
  JsonPrimitive,
  JsonValue,
  ModelMessage,
  ModelActivityEvent,
  ModelFinishReason,
  ModelOutputChunk,
  ModelOutputChunkEvent,
  ModelRequestEvent,
  ModelRequest,
  ModelResponse,
  ModelResponseEvent,
  MissionIntent,
  NormalizedStopReason,
  NormalizedQualityScore,
  ContinueTerminationDecision,
  Protocol,
  ProtocolConfig,
  ProtocolName,
  ProtocolSelection,
  PrimitiveTerminationCondition,
  ReplayTraceBudget,
  ReplayTraceBudgetStateChange,
  ReplayTraceFinalOutput,
  ReplayTraceProtocolDecision,
  ReplayTraceProtocolDecisionType,
  ReplayTraceProviderCall,
  ReplayTraceRunInputs,
  ReplayTraceSchemaVersion,
  ReplayTraceSeed,
  RemainingBudget,
  RoleAssignmentEvent,
  RunAccounting,
  RunEvaluation,
  RunEvaluator,
  RunEventLog,
  RunEvent,
  RunMetadata,
  RunResult,
  RunUsage,
  RuntimeTool,
  RuntimeToolAdapterContract,
  RuntimeToolAdapterError,
  RuntimeToolAdapterErrorCode,
  RuntimeToolCodeExecutionPermission,
  RuntimeToolCustomPermission,
  RuntimeToolError,
  RuntimeToolErrorResult,
  RuntimeToolExecutionContext,
  RuntimeToolExecutionRequest,
  RuntimeToolExecutor,
  RuntimeToolIdentity,
  RuntimeToolInputSchema,
  RuntimeToolNetworkPermission,
  RuntimeToolPermission,
  RuntimeToolResult,
  RuntimeToolSuccessResult,
  RuntimeToolTraceContext,
  RuntimeToolValidationInvalidResult,
  RuntimeToolValidationIssue,
  RuntimeToolValidationResult,
  RuntimeToolValidationValidResult,
  SharedProtocolConfig,
  SequentialProtocolConfig,
  StreamCompletionEvent,
  StreamErrorEvent,
  StreamEvent,
  StreamEventSubscriber,
  StreamHandle,
  StreamHandleStatus,
  StreamLifecycleEvent,
  StreamOutputEvent,
  StreamSubscription,
  StopTerminationDecision,
  SubRunBudgetClampedEvent,
  SubRunCompletedEvent,
  SubRunConcurrencyClampedEvent,
  SubRunFailedEvent,
  SubRunParentAbortedEvent,
  SubRunQueuedEvent,
  SubRunStartedEvent,
  TerminationCondition,
  TerminationDecision,
  TerminationEvaluationContext,
  TerminationStopRecord,
  Tier,
  ToolActivityEvent,
  ToolCallEvent,
  ToolResultEvent,
  Trace,
  Transcript,
  TranscriptEntry,
  TranscriptLink,
  TurnEvent,
  WrapUpHintConfig
} from "./types.js";
